/* ===================================================================
   Gallery page behaviour.

   Reads gallery-images.json (regenerated by update-gallery.py whenever
   photos are added to images/Portfolio/), builds the masonry grid, and
   drives a swipeable lightbox. Each entry carries the photo's real pixel
   dimensions, which go straight onto the <img> as width/height so the
   browser reserves the correct shape before the photo downloads — that is
   what keeps the grid from jumping around as images stream in on a phone.
   =================================================================== */
(function () {
    'use strict';

    var IMAGE_PATH = 'images/Portfolio/';
    var SWIPE_DISTANCE = 55;  // px of horizontal travel that commits a swipe
    var SWIPE_VELOCITY = 0.4; // px/ms — a quick flick commits at a shorter distance
    var CLOSE_DISTANCE = 110; // px of downward drag that dismisses the lightbox

    var photos = [];
    var current = 0;
    var lastFocused = null;

    var grid, status, lightbox, track, counter, slides;

    /* ---------- Grid ---------- */

    function load() {
        fetch('gallery-images.json')
            .then(function (response) {
                if (!response.ok) {
                    throw new Error('HTTP ' + response.status);
                }
                return response.json();
            })
            .then(function (data) {
                photos = normalise(data.images);
                if (!photos.length) {
                    showStatus('No photos yet — add some to images/Portfolio/.');
                    return;
                }
                render();
            })
            .catch(function (error) {
                console.error('Gallery failed to load:', error);
                showStatus('The gallery could not be loaded right now. Please refresh, or ' +
                    'get in touch and I\'ll send photos over directly.');
            });
    }

    // Accepts both the current {src, width, height} entries and the older
    // plain-filename format, so an out-of-date gallery-images.json still renders
    // (just without the pre-reserved tile shapes).
    function normalise(images) {
        if (!Array.isArray(images)) {
            return [];
        }
        return images.map(function (entry) {
            if (typeof entry === 'string') {
                return { src: entry, width: null, height: null };
            }
            return {
                src: entry.src,
                width: entry.width || null,
                height: entry.height || null
            };
        }).filter(function (photo) {
            return !!photo.src;
        });
    }

    function render() {
        var fragment = document.createDocumentFragment();

        photos.forEach(function (photo, index) {
            var tile = document.createElement('button');
            tile.type = 'button';
            tile.className = 'tile';
            tile.setAttribute('aria-label', 'View photo ' + (index + 1) + ' of ' + photos.length);
            tile.addEventListener('click', function () {
                open(index);
            });

            var img = document.createElement('img');
            img.src = IMAGE_PATH + photo.src;
            img.alt = '';
            img.loading = 'lazy';
            img.decoding = 'async';
            if (photo.width && photo.height) {
                img.width = photo.width;
                img.height = photo.height;
            }
            markLoaded(img);

            tile.appendChild(img);
            fragment.appendChild(tile);
        });

        grid.appendChild(fragment);
        status.hidden = true;
        layoutGrid();

        if (photos.length < 2) {
            lightbox.querySelector('.lightbox-prev').hidden = true;
            lightbox.querySelector('.lightbox-next').hidden = true;
        }
    }

    /* Give every tile a row span matching its photo's proportions.

       The grid in css/gallery.css is made of short fixed-height rows; a tile
       covers as many of them as its photo is tall. That is what produces the
       gapless masonry look while still laying tiles out left to right, which
       plain CSS multi-column could not do — it filled each column top to
       bottom, so the second photo on screen was the seventeenth in the
       gallery.

       Heights are worked out from the width/height in gallery-images.json
       rather than from the loaded image, so the layout is correct on first
       paint instead of reshuffling as photos stream in. */
    function layoutGrid() {
        if (!grid) {
            return;
        }

        var styles = window.getComputedStyle(grid);
        if (styles.display !== 'grid') {
            return; // Older browser falling back to normal block flow.
        }

        var gap = parseFloat(styles.rowGap) || 0;
        var unit = parseFloat(styles.gridAutoRows) || 0;
        if (!unit) {
            return; // No row unit to measure against; leave tiles as they are.
        }

        var tiles = grid.querySelectorAll('.tile');
        for (var i = 0; i < tiles.length; i++) {
            var tile = tiles[i];
            var img = tile.querySelector('img');
            var width = tile.getBoundingClientRect().width;
            var ratio = img && Number(img.getAttribute('height')) / Number(img.getAttribute('width'));
            // Fall back to whatever the tile currently measures if the photo's
            // dimensions are missing from the JSON.
            var height = (width && isFinite(ratio) && ratio > 0)
                ? width * ratio
                : tile.getBoundingClientRect().height;

            tile.style.gridRowEnd = 'span ' + Math.max(1, Math.ceil((height + gap) / (unit + gap)));
        }
    }

    // Column widths change with the viewport, so the spans have to be redone.
    // Debounced because resize fires continuously while a window is dragged.
    var relayoutTimer = null;
    function scheduleRelayout() {
        window.clearTimeout(relayoutTimer);
        relayoutTimer = window.setTimeout(layoutGrid, 120);
    }

    // Fade each photo in once it has actually decoded. Cached images can be
    // complete before the listener attaches, hence the up-front check.
    function markLoaded(img) {
        if (img.complete && img.naturalWidth) {
            img.classList.add('loaded');
            return;
        }
        img.addEventListener('load', function () {
            img.classList.add('loaded');
        });
        img.addEventListener('error', function () {
            img.classList.add('loaded');
            img.alt = 'Photo unavailable';
        });
    }

    function showStatus(message) {
        status.hidden = false;
        status.textContent = message;
    }

    /* ---------- Lightbox ---------- */

    function wrap(index) {
        return (index % photos.length + photos.length) % photos.length;
    }

    // Paints the three slides around `current`. Assigning the neighbours' src
    // is also how the next and previous photos get preloaded.
    function paint() {
        [-1, 0, 1].forEach(function (offset, slot) {
            var photo = photos[wrap(current + offset)];
            var img = slides[slot].firstElementChild;
            var src = IMAGE_PATH + photo.src;
            if (img.getAttribute('src') !== src) {
                img.src = src;
            }
        });
        counter.textContent = (current + 1) + ' / ' + photos.length;
    }

    function open(index) {
        lastFocused = document.activeElement;
        current = index;
        paint();
        lightbox.classList.add('open');
        document.body.classList.add('lightbox-open');
        lightbox.querySelector('.lightbox-close').focus();
    }

    function close() {
        lightbox.classList.remove('open');
        document.body.classList.remove('lightbox-open');
        if (lastFocused && lastFocused.focus) {
            lastFocused.focus();
        }
    }

    function isOpen() {
        return lightbox.classList.contains('open');
    }

    function setOffset(pixels) {
        track.style.transform = 'translate3d(calc(-33.3333% + ' + pixels + 'px), 0, 0)';
    }

    var animating = false;

    function go(direction) {
        if (animating || photos.length < 2) {
            return;
        }
        animating = true;

        // Slide the track by one full slot, then quietly recentre it on the new
        // photo once the animation lands — so the next swipe starts from home.
        var settle = function () {
            track.removeEventListener('transitionend', settle);
            clearTimeout(fallback);
            current = wrap(current + direction);
            track.classList.remove('animating');
            paint();
            void track.offsetWidth; // flush the class removal before resetting
            setOffset(0);
            animating = false;
        };
        var fallback = setTimeout(settle, 400); // in case transitionend never fires

        track.addEventListener('transitionend', settle);
        track.classList.add('animating');
        track.style.transform =
            'translate3d(' + (direction > 0 ? '-66.6666%' : '0%') + ', 0, 0)';
    }

    /* ---------- Swipe ---------- */

    function bindSwipe(stage) {
        var startX = 0, startY = 0, startTime = 0;
        var dragging = false;   // a horizontal drag has been committed to
        var deciding = false;   // touch is down but the axis is still unknown
        var wasSwipe = false;   // the click about to fire is the tail of a drag
        var pointerId = null;

        stage.addEventListener('pointerdown', function (event) {
            if (animating || event.button !== 0) {
                return;
            }
            pointerId = event.pointerId;
            startX = event.clientX;
            startY = event.clientY;
            startTime = Date.now();
            deciding = true;
            dragging = false;
        });

        stage.addEventListener('pointermove', function (event) {
            if (event.pointerId !== pointerId || (!deciding && !dragging)) {
                return;
            }
            var dx = event.clientX - startX;
            var dy = event.clientY - startY;

            // Wait for a few pixels of travel before deciding whether this is a
            // photo swipe or a vertical dismiss, so neither steals the other.
            if (deciding) {
                if (Math.abs(dx) < 8 && Math.abs(dy) < 8) {
                    return;
                }
                deciding = false;
                if (Math.abs(dx) <= Math.abs(dy)) {
                    return; // vertical — leave it to pointerup to maybe dismiss
                }
                dragging = true;
                stage.setPointerCapture(pointerId);
            }

            if (dragging) {
                event.preventDefault();
                setOffset(dx);
            }
        });

        function finish(event) {
            if (event.pointerId !== pointerId) {
                return;
            }
            var dx = event.clientX - startX;
            var dy = event.clientY - startY;
            var elapsed = Math.max(Date.now() - startTime, 1);
            var wasDragging = dragging;

            pointerId = null;
            deciding = false;
            dragging = false;
            wasSwipe = wasDragging;

            if (!wasDragging) {
                // A deliberate downward drag on the photo dismisses the lightbox,
                // matching how phone photo viewers behave.
                if (dy > CLOSE_DISTANCE && Math.abs(dy) > Math.abs(dx)) {
                    close();
                }
                return;
            }

            var flicked = Math.abs(dx) / elapsed > SWIPE_VELOCITY && Math.abs(dx) > 20;
            if (Math.abs(dx) > SWIPE_DISTANCE || flicked) {
                go(dx < 0 ? 1 : -1);
            } else {
                // Not far enough — spring back to the current photo.
                track.classList.add('animating');
                setOffset(0);
                setTimeout(function () {
                    track.classList.remove('animating');
                }, 300);
            }
        }

        // Clicking the dark space around a photo dismisses it, the way clicking
        // outside any modal does. The arrows sit inside the stage, so their
        // clicks bubble through here — they must not also be read as a click on
        // the backdrop, or tapping one would advance the photo and immediately
        // close the lightbox. A click that merely ends a swipe is ignored too.
        stage.addEventListener('click', function (event) {
            var endedASwipe = wasSwipe;
            wasSwipe = false;
            if (endedASwipe || event.target.closest('.lightbox-arrow')) {
                return;
            }
            if (event.target.tagName !== 'IMG') {
                close();
            }
        });

        stage.addEventListener('pointerup', finish);
        stage.addEventListener('pointercancel', function (event) {
            if (event.pointerId !== pointerId) {
                return;
            }
            pointerId = null;
            deciding = false;
            dragging = false;
            track.classList.add('animating');
            setOffset(0);
            setTimeout(function () {
                track.classList.remove('animating');
            }, 300);
        });
    }

    /* ---------- Wiring ---------- */

    function init() {
        grid = document.getElementById('gallery-grid');
        status = document.getElementById('gallery-status');
        lightbox = document.getElementById('lightbox');
        track = lightbox.querySelector('.lightbox-track');
        counter = lightbox.querySelector('.lightbox-counter');
        slides = Array.prototype.slice.call(lightbox.querySelectorAll('.lightbox-slide'));

        lightbox.querySelector('.lightbox-close').addEventListener('click', close);
        lightbox.querySelector('.lightbox-prev').addEventListener('click', function () {
            go(-1);
        });
        lightbox.querySelector('.lightbox-next').addEventListener('click', function () {
            go(1);
        });

        document.addEventListener('keydown', function (event) {
            if (!isOpen()) {
                return;
            }
            if (event.key === 'Escape') {
                close();
            } else if (event.key === 'ArrowLeft') {
                go(-1);
            } else if (event.key === 'ArrowRight') {
                go(1);
            }
        });

        bindSwipe(lightbox.querySelector('.lightbox-stage'));
        window.addEventListener('resize', scheduleRelayout);
        load();
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
}());
